name: Publish Extension

on:
  push:
    branches:
      - live

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 2
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Compile Extension
        run: npm run compile
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Publish to Open VSX
        run: npm run publish
        env:
          OVPAT: ${{ secrets.OVPAT }}
